### ISSUE TITLE
Opening the file in binary mode causes type error in Python 3

### ISSUE THREAD

**Issue by vdedyukhin** [nvie/cookiecutter-python-cli#3]
TypeError: endswith first arg must be bytes or a tuple of bytes, not str

Traceback (most recent call last):
  File "post_gen_project.py", line 21, in <mo
dule>
    main()
  File "post_gen_project.py", line 15, in main
    if not contents.endswith('\n'):

**Comment by bomattin** [comment]
+1

**Comment by nvie** [comment]
Fixed by #5.
